#!/usr/bin/env bash

# Start a new Tmux session named "secondary"
tmux new-session -s secondary -d

# Create the first window and split it vertically
tmux splitw -h -t secondary:1
tmux splitw -v -t secondary:1.2
tmux send-keys -t secondary:1.1 "cd ~/projects" C-m
tmux send-keys -t secondary:1.2 "cd ~/projects" C-m
tmux send-keys -t secondary:1.3 "cd ~/projects" C-m

# Create the second window
tmux new-window -t secondary:2
tmux send-keys -t secondary:2 "cd ~/projects" C-m

# Attach to the Tmux session
tmux attach -t secondary
