#!/usr/bin/env bash

# Start a new Tmux session named "stdSession"
tmux new-session -s stdSession -d

# Create the first window and split it vertically
tmux splitw -h -t stdSession:1
tmux splitw -v -t stdSession:1.2
tmux send-keys -t stdSession:1.1 "cd ~/projects" C-m
tmux send-keys -t stdSession:1.2 "cd ~/projects" C-m
tmux send-keys -t stdSession:1.3 "cd ~/projects" C-m

# Create the second window
tmux new-window -t stdSession:2
tmux send-keys -t stdSession:2 "cd ~/projects" C-m

# Attach to the Tmux session
tmux attach -t stdSession
